version: '3.7'
services:
  authorization:
    build:
      context: ./authorization-authentication
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      KAFKA_SERVER: kafka:9092

  transaction:
    build:
      context: ./transactionManager
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - postgres
      - kafka
  report:
    build:
      context: ./report
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - mongo
      - kafka
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      KAFKA_SERVER: kafka:9092
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction-manager

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
